parserOptions:
  ecmaVersion: 2018

env:
  es6: true
  node: true
  jest: true

overrides:
  - files: '*e2e.test.js'
    rules:
      max-nested-callbacks:
        - error
        - max: 4

extends: 'htmlacademy/node'
